### ISSUE TITLE
example.tab has 7 columns, only 5 defined in docs

### ISSUE THREAD

**Issue by stsmall** [gvbarroso/iSMC#1]
Hi @gvbarroso,
When I was trying to run ismc_mapper, I kept getting an error about the tab file being wrong. This was the same tab file I had used for the ismc run which finished without errors. When I added 2 more columns to the tab file, 6 and 7 which I just copied columns 2 and 5, the mapper ran to completion. What should be in the columns 6 and 7 of the tab file since the docs/example only discuss columns 1-5?
thank you,
@stsmall

**Comment by gvbarroso** [comment]
Hi @stsmall,

Thanks for bringing that up. You are correct that the 6th and 7th columns are required by ismc_mapper. In short, they represent optional cut-off positions where you can 'trim' the single-nucleotide maps before binning.
I have updated the documentation -- please take a look and let me know whether it is clear.

**Comment by stsmall** [comment]
Hi @gvbarroso,
thank you that is very clear and a cool feature.
thanks,
@stsmall
