### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by nomascus** [gvbarroso/iSMC#6]
Hi, I've been having some trouble installing iSMC. I've been following the INSTALL.txt and and have SimpleZipHMM installed on the cluster I am using (Red Hat Enterprise Linux Server release 6.7 (Santiago)), but iSMC dies when I run make. It gets to this step: [ 24%] Building CXX object src/CMakeFiles/ismc.dir/BaumWelch.cpp.o 

then dies at: 

> boost::bimaps::tags::tagged<const std::__cxx11::basic_string<char>, boost::bimaps::relation::member_at::right>, mpl_::na, true> > > > > > > > >::inherit2()’ first required here 
>          : data(d) {}
>                  ^
> make[2]: *** [src/CMakeFiles/ismc.dir/BaumWelch.cpp.o] Error 1
> make[1]: *** [src/CMakeFiles/ismc.dir/all] Error 2
> make: *** [all] Error 2

Do you have any idea what I should do here? I believe everything looks fine after CMAKE (below). Initially, I had some trouble with the BLAS modules on the cluster, but my my sysadmin recommended the following solution, which appears to have worked:

> $ cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -Dblas_INCLUDE_DIR=/apps/OPENBLAS/0.2.20/include -Dblas_LIBRARY=/apps/OPENBLAS/0.2.20/lib/libblas.so -DUSE_LIBSIMPLEZIPHMM=true 
>
> -- The CXX compiler identification is GNU 6.3.0
> -- Check for working CXX compiler: /apps/GCC/6.3.0/bin/c++
> -- Check for working CXX compiler: /apps/GCC/6.3.0/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- bpp-core 4.1.0 found:
> --   static lib: /apps/BIOPP/2.4.0/lib64/libbpp-core.a
> --   shared lib: /apps/BIOPP/2.4.0/lib64/libbpp-core.so.4.1.0
> --   includes: /apps/BIOPP/2.4.0/include
> -- bpp-seq 12.0.0 found:
> --   static lib: /apps/BIOPP/2.4.0/lib64/libbpp-seq.a
> --   shared lib: /apps/BIOPP/2.4.0/lib64/libbpp-seq.so.12.0.0
> --   includes: /apps/BIOPP/2.4.0/include
> -- bpp-phyl 12.0.0 found:
> --   static lib: /apps/BIOPP/2.4.0/lib64/libbpp-phyl.a
> --   shared lib: /apps/BIOPP/2.4.0/lib64/libbpp-phyl.so.12.0.0
> --   includes: /apps/BIOPP/2.4.0/include
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> -- simpleziphmm 1.0.0 found:
> --   static lib: /home/devel/jorkin/.local/lib64/libsimpleziphmm.a
> --   shared lib: /home/devel/jorkin/.local/lib64/libsimpleziphmm.so.1.0.0
> --   includes: /home/devel/jorkin/.local/include
> -- Boost version: 1.63.0
> -- Found the following Boost libraries:
> --   iostreams
> --   regex
> -- Boost libraries found here:
>    includes: /apps/BOOST/1_63_0/AVX0/GCC/include
>    dynamic libraries: /apps/BOOST/1_63_0/AVX0/GCC/lib/libboost_iostreams.so;/apps/BOOST/1_63_0/AVX0/GCC/lib/libboost_regex.so
> -- Library z found here:
>    includes: /usr/include
>    dynamic libraries: /usr/lib64/libz.so
> -- Library bz2 found here:
>    includes: /usr/include
>    dynamic libraries: /usr/lib64/libbz2.so
> -- Library blas found here:
>    includes: /apps/OPENBLAS/0.2.20/include
>    dynamic libraries: /apps/OPENBLAS/0.2.20/lib/libblas.so
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/devel/scratch/programs/iSMC

**Comment by gvbarroso** [comment]
It looks like it's pointing to Boost somehow, but I've never encountered this error before, I am sorry.

Are you able to install it in your local machine? A practical "solution" could be to compile it statically and the copy the executable to the cluster. Would you be able to do that?
